-----------------------------------------
-- LOCALIZED GLOBAL VARIABLES
-----------------------------------------

local CGV = _G.CGV
local Data = {}
local Travel

-----------------------------------------
-- SAVED REFERENCES
-----------------------------------------

Travel = CGV.Travel
Travel.Data = Data

-----------------------------------------
-- MAP DATA
-----------------------------------------

--[[
	\s*(\[.*\]) = ([0-9]*),\n  	->	\t\1 = \2,\n
	\t(\[.*\]) = ([0-9]*)		->	\t\2##\1 = \2
	\t[0-9]*##			->	\t
--]]


Data.MapIdsByName = {
   -- Aldmeri Dominion
   -- Khenarthi's Roost    
   ["Khenarthi's Roost"]                   =   1,
   ["Temple of the Mourning Springs"]      =   2,
   ["Hazak's Lair"]                        =   3,
   ["Shattered Shoals"]                    =   4,
   ["The Mangroves"]                       =   5,
   ["Mistral"]                             =   6,
   ["Cat's Eye Quay"]                      =   7,

   -- Auridon
   ["Vulkhel Guard"]                       =   8,
   ["Vulkhel Guard Outlaws Refuge"]        =   9,
   ["Auridon"]                             =  10,
   ["Del's Claim"]                         =  11,
   ["Ondil"]                               =  12,
   ["Phaer Catacombs"]                     =  13,
   ["Inner Tanzelwil"]                     =  14,
   ["Tower of the Vale - Temple"]          =  15,
   ["Tower of the Vale - Rage"]            =  16,
   ["Merion's Bliss - Lower"]              =  17,
   ["Merion's Bliss - Upper"]              =  18,
   ["Tower of the Vale - Despair"]         =  19,
   ["Sanessalmo's Lair"]                   =  20,
   ["Entila's Folly"]                      =  21,
   ["Smuggler's Tunnel"]                   =  22,
   ["Skywatch"]                            =  23,
   ["Skywatch Sanctum"]                    =  24,
   ["The Veiled Keep"]                     =  25,
   ["Ezduiin Undercroft"]                  =  26,
   ["Wansalen"]                            =  27,
   ["Quendeluum South Ruins"]              =  28,
   ["Abadoned Mine"]                       =  29,
   ["Bewan"]                               =  30,
   ["Saltspray Cave"]                      =  31,
   ["Torinaan Central Shrine"]             =  32,
   ["Torinaan Shrines"]                    =  33,
   ["Mehrunes' Spite"]                     =  34,
   ["The Vault of Exile"]                  =  35,
   ["Firsthold"]                           =  36,
   ["The Refuge of Dredd"]                 =  37,

   -- Grahtwood
   ["Grahtwood"]                           =  38,
   ["Haven"]                               =  39,
   ["The Aquifer"]                         =  40,
   ["Sacred Leap Grotto"]                  =  41,
   ["The Scuttle Pit"]                     =  42,
   ["Brackenleaf"]                         =  43,
   ["Elden Root"]                          =  44,
   ["Elden Root Outlaws Refuge"]           =  45,
   ["Cave of Broken Sails"]                =  46,
   ["Gray Mire"]                           =  47,
   ["Barrowbough"]                         =  48,
   ["Cathedral of the Golden Path"]        =  49,
   ["Ne Salas"]                            =  50,
   ["Mobar Mine"]                          =  51,
   ["The Middens"]                         =  52,
   ["Vinedeath Cave"]                      =  53,
   ["Ossuary of Telacar"]                  =  54,
   ["Laeloria Ruins"]                      =  55,
   ["Karthdar"]                            =  56,
   ["Cormount Prison"]                     =  57,
   ["Reliquary Ruins"]                     =  58,
   ["Reliquary Vault"]                     =  59,
   ["Ancient Cave"]                        =  60,
   ["Faltonia's Mine"]                     =  61,
   ["Barkbite Cave"]                       =  62,
   ["Barkbite Mine"]                       =  63,
   ["Refur Trading Post"]                  =  64,
   ["Tomb of Anahbi"]                      =  65,
   ["Burroot Kwama Mine"]                  =  66,
   ["Gil-Var-Delle Abandoned Cave"]        =  67,
   ["Nairume's Prison"]                    =  68,
   ["The Orrery"]                          =  69,
   ["Wormroot Depths"]                     =  70,

   -- Greenshade
   ["Marbruk"]                             =  71,
   ["Marbruk Outlaws Refuge"]              =  72,
   ["Greenshade"]                          =  73,
   ["Guzrag's Mine"]                       =  74,
   ["Camp Gushnukbur"]                     =  75,
   ["Shrouded Hollow"]                     =  76,
   ["Fading Tree"]                         =  77,
   ["Carac Dena"]                          =  78,
   ["Silatar"]                             =  79,
   ["Hollow Den"]                          =  80,
   ["Shademist Enclave"]                   =  81,
   ["Naril Nagaia"]                        =  82,
   ["Woodhearth"]                          =  83,
   ["Imperial Underground"]                =  84,
   ["Ilmyris"]                             =  85,
   ["Serpent's Grotto"]                    =  86,
   ["The Underroot"]                       =  87,
   ["Abecean Sea"]                         =  88,
   ["Old Merchant Caves"]                  =  89,
   ["Harridan's Lair"]                     =  90,
   ["Nereid Temple Cave"]                  =  91,
   ["Falinesti Cave"]                      =  92,
   ["Hectahame Grotto"]                    =  93,
   ["Isles of Torment"]                    =  94,
   ["Barrow Trench"]                       =  95,

   -- Malabal Torinaan
   ["Malabal Tor"]                         =  96,
   ["Velyn Harbor"]                        =  97,
   ["Velyn Harbor Outlaws Refuge"]         =  98,
   ["Stormwarden Undercroft"]              =  99,
   ["Dead Man's Drop"]                     = 100,
   ["Tomb of the Apostates"]               = 101,
   ["Hoarvor Pit"]                         = 102,
   ["Vulkwasten"]                          = 103,
   ["Ogrim's Yawn"]                        = 104,
   ["Abamath Ruins"]                       = 105,
   ["Shrine of Mauloch"]                   = 106,
   ["Shael Ruins"]                         = 107,
   ["Belarata"]                            = 108,
   ["Roots of Silvenar"]                   = 109,
   ["Ouze"]                                = 110,
   ["Baandari Trading Post"]               = 111,
   ["Roots of Treehenge"]                  = 112,
   ["Black Vine Ruins"]                    = 113,
   ["The Hunting Grounds"]                 = 114,
   ["Silvenar Throne Room"]                = 115,
   ["Nchuleftingth Approach"]              = 116,

   -- Reapers March
   ["Reapers March"]                       = 117,
   ["Vinedusk Village Corridor"]           = 118,
   ["Vinedusk Village"]                    = 119,
   ["Khaj Rawlith"]                        = 120,
   ["Senalana"]                            = 121,
   ["Arenthia"]                            = 122,
   ["Greenhill Catacombs"]                 = 123,
   ["Thibaut's Cairn"]                     = 124,
   ["Halls of Ichor"]                      = 125,
   ["Rawl'kha"]                            = 126,
   ["Rawl'kha Outlaws Refuge"]             = 127,
   ["Rawl'kha Temple"]                     = 128,
   ["Weeping Wind Cave"]                   = 129,
   ["Moonmont Temple"]                     = 130,
   ["Do'Krin Temple"]                      = 131,
   ["The Five Finger Dance"]               = 132,
   ["Claw's Strike"]                       = 133,
   ["Old S'ren-ja Cave"]                   = 134,
   ["Rainshadow Cave"]                     = 135,
   ["Cleft Rock Cave"]                     = 136,
   ["Jode's Light"]                        = 137,
   ["Kuna's Delve"]                        = 138,
   ["Ren-dro Caverns"]                     = 139,
   ["Fort Sphinxmoth"]                     = 140,
   ["Fardir's Folly"]                      = 141,
   ["Dune"]                                = 142,
   ["Temple of the Dance"]                 = 143,
   ["The Demi-Plane of Jode"]              = 144,
   ["The Wild Hunt"]                       = 145,
   ["Urcelmo's Betryal"]                   = 146,
   ["Den of Lorkhaj"]                      = 147,

   -- Daggerfall Covenant
   -- Stros M'Kai
   ["Port Hunding"]                        = 148,
   ["The Grave"]                           = 149,
   ["Stros M'Kai"]                         = 150,
   ["Goblin Mines"]                        = 151,
   ["Bthzark"]                             = 152,

   -- Betnikh
   ["Stonetooth Fortress"]                 = 153,
   ["Betnikh"]                             = 154,
   ["Bloodthorn Lair"]                     = 155,
   ["Ancient Carzog's Demise"]             = 156,
   ["Moriseli"]                            = 157,
   ["Carzog's Demise"]                     = 158,

   -- Glenumbra
   ["Daggerfall"]                          = 159,
   ["Glenumbra"]                           = 160,
   ["Daggerfall Outlaws Refuge"]           = 161,
   ["Ilessan Tower"]                       = 162,
   ["East Hut Portal Cave"]                = 163,
   ["South Hut Portal Cave"]               = 164,
   ["West Hut Portal Cave"]                = 165,
   ["North Hut Portal Cave"]               = 166,
   ["Silumm"]                              = 167,
   ["Enduum"]                              = 168,
   ["Dresan Keep"]                         = 169,
   ["Aldcroft"]                            = 170,
   ["Mines of Khuras"]                     = 171,
   ["Desolation's End"]                    = 172,
   ["Ebon Crypt"]                          = 173,
   ["Cath Bedraud"]                        = 174,
   ["Angof's Sanctum"]                     = 175,
   ["Tomb of Lost Kings"]                  = 176,
   ["Cryptwatch Fort"]                     = 177,
   ["Crosswych"]                           = 178,
   ["Crosswych Mine"]                      = 179,

   -- Stormhaven
   ["Stormhaven"]                          = 180,
   ["Koeglin Village"]                     = 181,
   ["Alcaire Castle"]                      = 182,
   ["Windridge Cave"]                      = 183,
   ["Portdun Watch"]                       = 184,
   ["Koeglin Mine"]                        = 185,
   ["Pariah Catacombs"]                    = 186,
   ["Wayrest"]                             = 187,
   ["Wayrest Outlaws Refuge"]              = 188,
   ["Farangel's Delve"]                    = 189,
   ["Bearclaw Mine"]                       = 190,
   ["Godrun's Dream"]                      = 191,
   ["Norvulk Ruins"]                       = 192,
   ["Aphren's Tomb"]                       = 193,
   ["Emeric's Dream"]                      = 194,

   -- Rivenspire
   ["Rivenspire"]                          = 195,
   ["Shornhelm"]                           = 196,
   ["Shornhelm Outlaws Refuge"]            = 197,
   ["Fevered Mews"]                        = 198,
   ["Crestshade Mine"]                     = 199,
   ["Doomcrag Shrouded Pass"]              = 200,
   ["Shadowfate Cavern"]                   = 201,
   ["Hoarfrost Downs"]                     = 202,
   ["Tribulation Crypt"]                   = 203,
   ["Lorkrata Ruins"]                      = 204,
   ["Edrald Undercroft"]                   = 205,
   ["Flyleaf Catacombs"]                   = 206,
   ["Northpoint"]                          = 207,
   ["Breagha-Fin"]                         = 208,
   ["Orc's Finger Ruins"]                  = 209,
   ["Hildune's Secret Refuge"]             = 210,
   ["Erokii Ruins"]                        = 211,
   ["Shrouded Pass"]                       = 212,
   ["Doomcrag"]                            = 213,
   ["Obsidian Scar"]                       = 214,

   -- Alik'r Desert
   ["Sentinel"]                            = 215,
   ["Sentinel Outlaws Refuge"]             = 216,
   ["Alik'r Desert"]                       = 217,
   ["Shore Cave"]                          = 218,
   ["Impervious Vault"]                    = 219,
   ["Santaki"]                             = 220,
   ["Salas En"]                            = 221,
   ["The Portal Chamber"]                  = 222,
   ["Ash'abah Pass"]                       = 223,
   ["Yokudan Palace"]                      = 224,
   ["Divad's Chagrin Mine"]                = 225,
   ["Bergama"]                             = 226,
   ["Magistrate's Basement"]               = 227,
   ["Aldunz"]                              = 228,
   ["The Master's Crypt"]                  = 229,
   ["Kulati Mines"]                        = 230,
   ["Coldrock Diggings"]                   = 231,
   ["Sandblown Mine"]                      = 232,
   ["Yldzuun"]                             = 233,
   ["Kozanset"]                            = 234,
   ["Smuggler King's Tunnel"]              = 235,
   ["Suturah's Crypt"]                     = 236,
   ["Lost City of the Na- Totambu"]        = 237,

   -- Bangkorai
   ["Evermore"]                            = 238,
   ["Evermore Outlaws Refuge"]             = 239,
   ["Bangkorai"]                           = 240,
   ["Bisnensel"]                           = 241,
   ["Torog's Spite"]                       = 242,
   ["Crypt of the Exiles"]                 = 243,
   ["Troll's Toothpick"]                   = 244,
   ["Nchu Duabthar Threshold"]             = 245,
   ["Viridian Watch"]                      = 246,
   ["Bangkorai Garrison"]                  = 247,
   ["Sunken Road"]                         = 248,
   ["Klathzgar"]                           = 249,
   ["Rubble Butte"]                        = 250,
   ["Nilata Ruins"]                        = 251,
   ["Anexiel's Lair"]                      = 252,
   ["Hallin's Stand"]                      = 253,
   ["Onsi's Breath Mine"]                  = 254,
   ["Hall of Heroes"]                      = 255,
   ["The Far Shores"]                      = 256,

   -- Ebonheart Pact
   -- Bleakrock Isle
   ["Bleakrock Village"]                   = 257,
   ["Bleakrock Isle"]                      = 258,
   ["Skyshroud Barrow"]                    = 259,
   ["Hozzin's Folly"]                      = 260,
   ["Orkey's Hollow"]                      = 261,
   ["Last Rest"]                           = 262,

   -- Stonefalls
   ["Bal Foyen"]                           = 263,
   ["Dhalmora"]                            = 264,
   ["Smuggler's Tunnel"]                   = 265,
   ["Stonefalls"]                          = 266,
   ["Davon's Watch"]                       = 267,
   ["House Indoril Crypt"]                 = 268,
   ["Davon's Watch Outlaws Refuge"]        = 269,
   ["Charred Ridge"]                       = 270,
   ["Ash Mountain"]                        = 271,
   ["Inner Sea Armature"]                  = 272,
   ["Emberflint Mine"]                     = 273,
   ["Mephala's Nest"]                      = 274,
   ["Fort Arand Dungeons"]                 = 275,
   ["Ebonheart"]                           = 276,
   ["Coral Heart Chamber"]                 = 277,
   ["Hightide Hollow"]                     = 278,
   ["Heimlyn Keep Reliquary"]              = 279,
   ["Fort Virak Ruin"]                     = 280,
   ["Iliath Temple Mines"]                 = 281,
   ["Sheogorath's Tongue"]                 = 282,
   ["Kragenmoor"]                          = 283,
   ["House Dres Crypts"]                   = 284,
   ["Softloam Cavern"]                     = 285,
   ["Tormented Spire"]                     = 286,

   -- Deshaan
   ["Deshaan"]                             = 287,
   ["Quarantine Serk Catacombs"]           = 288,
   ["Narsis"]                              = 289,
   ["Narsis Ruins"]                        = 290,
   ["Lady Llarel's Shelter"]               = 291,
   ["Obisdian Gorge"]                      = 292,
   ["Apothacarium"]                        = 293,
   ["Mzithumz"]                            = 294,
   ["Mournhold"]                           = 295,
   ["Mournhold Outlaws Refuge"]            = 296,
   ["Mournhold Sewers"]                    = 297,
   ["The Triple Circle Mine"]              = 298,
   ["Tribunal Temple"]                     = 299,
   ["Bthanual"]                            = 300,
   ["Lower Bthanual"]                      = 301,
   ["Deepcrag Den"]                        = 302,
   ["Shad Astula Underhalls"]              = 303,
   ["Taleon's Crag"]                       = 304,
   ["Vale of the Ghost Snake"]             = 305,
   ["Tal'Deic Crypts"]                     = 306,
   ["The Shrine of St. Veloth"]            = 307,
   ["The Corpse Garden"]                   = 308,
   ["Knife Ear Grotto"]                    = 309,
   ["Eidolon's Hollow"]                    = 310,
   ["Reservoir of Souls"]                  = 311,
   ["Forgotten Crypts"]                    = 312,
   ["Sondivel's Lair"]                     = 313,

   -- Shadowfen
   ["Shadowfen"]                           = 314,
   ["Stormhold"]                           = 315,
   ["Stormhold Guild Hall"]                = 316,
   ["Stormhold Mortuary"]                  = 317,
   ["Silyanorn Ruins"]                     = 318,
   ["Stormhold Outlaws Refuge"]            = 319,
   ["Shrine of the Black Maw"]             = 320,
   ["Odious Chapel"]                       = 321,
   ["Mud Tree Mine"]                       = 322,
   ["Mudshallow Cave"]                     = 323,
   ["Ruins of Ten-Maur-Wolk"]              = 324,
   ["Lair of the Skin Stealer"]            = 325,
   ["Alten Corimont"]                      = 326,
   ["Tsanji's Hideout"]                    = 327,
   ["Atanaz Ruins"]                        = 328,
   ["Broken Tusk"]                         = 329,
   ["Onkobra Kwama Mine"]                  = 330,
   ["Percolating Mire"]                    = 331,
   ["Sunscale Ruins"]                      = 332,
   ["Grandranen Ruins"]                    = 333,
   ["Hissmir Ruins"]                       = 334,
   ["Temple of Sul"]                       = 335,
   ["White Rose Prison Dungeon"]           = 336,
   ["Child-Moska Ruins"]                   = 337,
   ["Loriasel"]                            = 338,
   ["Vision of the Hist"]                  = 339,

   -- Eastmarch
   ["Windhelm"]                            = 340,
   ["Windhelm Outlaws Refuge"]             = 341,
   ["Eastmarch"]                           = 342,
   ["The Chill Hollow"]                    = 343,
   ["Hall of Trials"]                      = 344,
   ["Icehammer's Vault"]                   = 345,
   ["Fort Morvunskar"]                     = 346,
   ["Giant's Run"]                         = 347,
   ["Fort Amol"]                           = 348,
   ["Lost Knife Cave"]                     = 349,
   ["The Frigid Grotto"]                   = 350,
   ["Bonestrewn Crest"]                    = 351,
   ["Wittestadr Crypts"]                   = 352,
   ["Mistwatch Crevasse"]                  = 353,
   ["Old Sord's Cave"]                     = 354,
   ["Stormcrag Crypt"]                     = 355,
   ["The Bastard's Tomb"]                  = 356,
   ["Mzulft"]                              = 357,
   ["Cragwallow"]                          = 358,

   -- The Rift
   ["Shor's Stone"]                        = 359,
   ["The Rift"]                            = 360,
   ["Shor's Stone Mine"]                   = 361,
   ["Fallowstone Vault"]                   = 362,
   ["Northwind Mine"]                      = 363,
   ["Vaults of Vernim"]                    = 364,
   ["Snapleg Cave"]                        = 365,
   ["Nimalten"]                            = 366,
   ["Nimalten Barrow"]                     = 367,
   ["Shroud Hearth Barrow"]                = 368,
   ["Pinepeak Caverns"]                    = 369,
   ["Taarengrav"]                          = 370,
   ["Arcwind Point"]                       = 371,
   ["Avanchnzel"]                          = 372,
   ["Riften"]                              = 373,
   ["Riften Outlaws Refuge"]               = 374,
   ["Fort Greenwall"]                      = 375,
   ["Faldar's Tooth"]                      = 376,
   ["Lost Prospect"]                       = 377,
   ["Broken Helm Hollow"]                  = 378,
   ["Dragon Cult Temple"]                  = 379,
   ["Trolhetta Cave"]                      = 380,
   ["Trolhetta Summit"]                    = 381,

   -- Coldharbour
   ["Stirk"]                               = 382,
   ["Coldharbour"]                         = 383,
   ["The Hollow City"]                     = 384,
   ["Tower of Lies"]                       = 385,
   ["The Grotto of Depravity"]             = 386,
   ["Haj Uxith"]                           = 387,
   ["Library of Dusk"]                     = 388,
   ["Lightless Oubliette"]                 = 389,
   ["Lightless Cell"]                      = 390,
   ["Aba-Loria"]                           = 391,
   ["The Vile Laboratory"]                 = 392,
   ["Holding Cells"]                       = 393,
   ["The Cave of Trophies"]                = 394,
   ["The Vault of Haman Forgefire"]        = 395,
   ["Thane's Lair"]                        = 396,
   ["The Black Forge"]                     = 397,
   ["The Great Shackle"]                   = 398,
   ["The Mooring"]                         = 399,
   ["Grunda's Gatehouse"]                  = 400,
   ["Mal Sorra's Tomb"]                    = 401,
   ["The Manor of Revelry"]                = 402,
   ["The Manor of Revelry Cave"]           = 403,
   ["The Wailing Maw"]                     = 404,
   ["The Lost Fleet"]                      = 405,
   ["Reaver Citadel Pyramid"]              = 406,
   ["The Endless Stair"]                   = 407,

   -- Five Companions
   ["The Wailing Prison"]                  = 408,
   ["The Harborage"]                       = 409,
   ["Vision of the Companions"]            = 410,
   ["The Foundry of Woe"]                  = 411,
   ["The Worm's Retreat"]                  = 412,
   ["Castle of the Worm"]                  = 413,
   ["The Halls of Torment"]                = 414,
   ["The Valley of Blades"]                = 415,
   ["Sancre Tor"]                          = 416,
   ["Heart's Grief"]                       = 417,
   ["The Colored Rooms"]                   = 418,

   -- Fighters Guild
   ["Buraniim"]                            = 419,
   ["Dourstone Vault"]                     = 420,
   ["Stonefang Cavern"]                    = 421,
   ["Mzeneldt"]                            = 422,
   ["Abagarlas"]                           = 423,
   ["The Earth Forge"]                     = 424,
   ["Ragnthar"]                            = 425,
   ["Halls of Submission"]                 = 426,

   -- Mages Guild
   ["Cheesemonger's Hollow"]               = 427,
   ["Shivering Isles"]                     = 428,
   ["Vuldngrav"]                           = 429,
   ["Asakala"]                             = 430,
   ["Circus of Cheerful Slaughter"]        = 431,
   ["Chateau of the Ravenous Rodent"]      = 432,
   ["Chateau Master Bedroom"]              = 433,
   ["Eyevea"]                              = 434,

   -- Cyrodiil
   ["Western Elsweyr Gate"]                = 435,
   ["Eastern Elsweyr Gate"]                = 436,
   ["Southern High Rock Gate"]             = 437,
   ["Northern High Rock Gate"]             = 438,
   ["Northern Morrowind Gate"]             = 439,
   ["Southern Morrowind Gate"]             = 440,
   ["Cyrodiil"]                            = 441,

   -- Imperial City
   ["Irrigation Tunnels"]                  = 442,
   ["Lambent Passage"]                     = 443,
   ["Harena Hypogeum"]                     = 444,
   ["Imperial City"]                       = 445,
   ["Dragonfire Cathedral"]                = 446,

   -- Craglorn
   ["Belkarth"]                            = 447,
   ["Belkarth Outlaws Refuge"]             = 448,
   ["Craglorn"]                            = 449,
   ["Buried Sands"]                        = 450,
   ["Tombs of the Na'Totambu"]             = 451,
   ["Haddock's Market"]                    = 452,
   ["Frost Monarch Lair"]                  = 453,
   ["Storm Lair"]                          = 454,
   ["Molavar"]                             = 455,
   ["Balamath"]                            = 456,
   ["Balamath Library"]                    = 457,
   ["Balamath Hall"]                       = 458,
   ["Reinhold's Retreat"]                  = 459,
   ["Dragonstar"]                          = 460,
   ["Fearfangs Caverns"]                   = 461,
   ["Sunken Lair"]                         = 462,
   ["Serpent's Nest"]                      = 463,
   ["Ilthag's Undertower"]                 = 464,
   ["Exarch's Stronghold"]                 = 465,
   ["The Howling Sepulchers"]              = 466,
   ["Loth'Na Caverns"]                     = 467,
   ["Skyreach Temple"]                     = 468,
   ["Apex Stone Room"]                     = 469,
   ["Rkundzelft"]                          = 470,
   ["Hircine's Haunt"]                     = 471,
   ["Elinhir Sewerworks"]                  = 472,
   ["Mtharnaz"]                            = 473,
   ["Ruins of Kardala"]                    = 474,
   ["Chiselshriek Mine"]                   = 475,
   ["Rkhardahrk"]                          = 476,
   ["Zalgaz's Den"]                        = 477,

   -- Orsinium
   ["Wrothgar"]                            = 478,
   ["Nikolvara's Kennel"]                  = 479,
   ["Orsinium"]                            = 480,
   ["Orsinium Outlaws Refuge"]             = 481,
   ["Frostbreak Fortress"]                 = 482,
   ["Ice-Heart's Lair"]                    = 483,
   ["Scarp Keep"]                          = 484,
   ["Throne Room"]                         = 485,
   ["Temple of Ire"]                       = 486,
   ["Temple of Ire Rectory"]               = 487,
   ["Graystone Quarry Depths"]             = 488,
   ["Honor's Rest"]                        = 489,
   ["Arakaul's Memory"]                    = 490,
   ["Tamahl's Memory"]                     = 491,
   ["Reliana's Memory"]                    = 492,
   ["Bloody Knoll"]                        = 493,
   ["Coldperch Cavern"]                    = 494,
   ["Bonerock Caverns"]                    = 495,
   ["Morkul Stronghold"]                   = 496,
   ["Morkul Descent"]                      = 497,
   ["Morkuldin"]                           = 498,
   ["Exile's Barrow"]                      = 499,
   ["Zthenganaz"]                          = 500,
   ["Fharun Prison"]                       = 501,
   ["Fharun Stronghold"]                   = 502,
   ["Path of the Faithful"]                = 503,
   ["Sanctuary of Malacath"]               = 504,
   ["Sorrow"]                              = 505,
   ["Argent Mine"]                         = 506,
   ["Thukhozod's Sanctum"]                 = 507,
   ["Watcher's Hold"]                      = 508,
   ["Paragon's Remembrance"]               = 509,
   ["Chambers Of Loyalty"]                 = 510,
   ["Path to the Moot Library"]            = 511,
   ["Path to the Moot"]                    = 512,

   -- Thieves Guild
   ["Fulstrom Homestead"]                  = 513,
   ["Fulstrom Catacombs"]                  = 514,
   ["Abah's Landing"]                      = 515,
   ["Maw of Lorkhaj"]                      = 516,
   ["Thieves Den"]                         = 517,
   ["Hew's Bane"]                          = 518,
   ["Sulima Mansion"]                      = 519,
   ["Bahraha's Gloom"]                     = 520,
   ["Iron Wheel Headquarters"]             = 521,
   ["al-Danobia"]                          = 522,
   ["al-Danobia Tomb"]                     = 523,
   ["Shark's Teeth Grotto"]                = 524,
   ["Hubalajad Palace"]                    = 525,

   -- Dark Brotherhood
   ["Anvil"]                               = 526,
   ["Anvil Outlaws Refuge"]                = 527,
   ["Gold Coast"]                          = 528,
   ["Jarol Estate Wine Cellar"]            = 529,
   ["Jarol Estate Smuggling Tunnels"]      = 530,
   ["Hrota Cave"]                          = 531,
   ["Garlas Agea"]                         = 532,
   ["Dark Brotherhood Sanctuary"]          = 533,
   ["Kvatch"]                              = 534,
   ["At-Himah Estate"]                     = 535,
   ["At-Himah Estate Caves"]               = 536,
   ["Jerall Mountains"]                    = 537,
   ["Anvil Castle"]                        = 538,
   ["Castle Kvatch"]                       = 539,
   ["Castle Kvatch Vaults"]                = 540,
   ["Castle Kvatch Passage"]               = 541,
   ["Enclave of the Hourglass"]            = 542,
   ["Blackwood Borderlands"]               = 543,
   ["Xith-Izkul Sanctuary"]                = 544,
   ["Knightsgrave"]                        = 545,
   ["Cathedral of Akatosh"]                = 546,

   -- Vvardenfell
   ["Cold-Blood Cavern"]                   = 547,
   ["Dyzera's Realm"]                      = 548,
   ["Vvardenfell"]                         = 549,
   ["Andrano Ancestral Tomb"]              = 550,
   ["Vivec City"]                          = 551,
   ["Vivec City Outlaws Refuge"]           = 552,
   ["Palace Receiving Room"]               = 553,
   ["Lord Vivec's Chambers"]               = 554,
   ["Library of Vivec"]                    = 555,
   ["Archcanon's Office"]                  = 556,
   ["Hall of Justice"]                     = 557,
   ["Sadrith Mora"]                        = 558,
   ["Dreloth Ancestral Tomb"]              = 559,
   ["Matus-Akin Egg Mine"]                 = 560,
   ["Barilzar's Tower"]                    = 561,
   ["Zaintiraris"]                         = 562,
   ["Dreudurai Glass Mine"]                = 563,
   ["Pulk"]                                = 564,
   ["Pinsun"]                              = 565,
   ["Zalkin-Sul Egg Mine"]                 = 566,
   ["Mzanchend"]                           = 567,
   ["Vassamsi Mine"]                       = 568,
   ["Tusenend"]                            = 569,
   ["Bal Ur"]                              = 570,
   ["Inanius Egg Mine"]                    = 571,
   ["Zainsipilu"]                          = 572,
   ["Firemoth Island"]                     = 573,
   ["Balmora"]                             = 574,
   ["Shulk Ore Mine"]                      = 575,
   ["Vassir-Didanat Mine"]                 = 576,
   ["Ashurnibibi"]                         = 577,
   ["Mallapi Cave"]                        = 578,
   ["Kudanant Mine"]                       = 579,
   ["Redoran Garrison"]                    = 580,
   ["Khartag Point"]                       = 581,
   ["Veloth Ancestral Tomb"]               = 582,
   ["Ramimilk"]                            = 583,
   ["Ashimanu Cave"]                       = 584,
   ["Hleran Ancestral Tomb"]               = 585,
   ["Bal Fell"]                            = 586,
   ["Gnisis Egg Mine"]                     = 587,
   ["Ashalmawia"]                          = 588,
   ["Prison of Xykenaz"]                   = 589,
   ["Cavern of the Incarnate"]             = 590,
   ["Skar"]                                = 591,
   ["Galom Daeus"]                         = 592,
   ["Nchuleft"]                            = 593,
   ["Nchuleft Depths"]                     = 594,
   ["Arkngthunch-Sturdumz"]                = 595,
   ["Kaushtarari"]                         = 596,
   ["Seht's Vault"]                        = 597,
   ["Maintenance Junction"]                = 598,
   ["Engineering Junction"]                = 599,
   ["The Divinity Atelier"]                = 600,
   ["Dockworks"]                           = 601,
   ["Engineering Access"]                  = 602,
   ["Atelier Courtyard"]                   = 603,
   ["Clavicus Vile Shrine"]                = 604,
	
   -- Clockwork City
   ["Dranil Kir Island"]                   = 605,
   ["Clockwork City Vaults"]               = 606,
   ["Clockwork City"]                      = 607,
   ["Brass Fortress"]                      = 608,
   ["Clockwork Basilica"]                  = 609,
   ["Serviflume"]                          = 610,
   ["Administration Nexus"]                = 611,
   ["Mechanical Fundament"]                = 612,
   ["Ventral Terminus"]                    = 613,
   ["Incarnatorium"]                       = 614,
   ["The Shadow Cleft"]                    = 615,
   ["Mnemonic Planisphere"]                = 616,
   ["Slag Town Outlaws Refuge"]            = 617,
   ["Evergloam"]                           = 618,
   ["Cogitum Centralis"]                   = 619,
   ["Everwound Wellspring"]                = 620,
   ["Halls of Regulation"]                 = 621,
	
   -- SUMMERSET
   ["Shimmerene"]                          = 622,
   ["Summerset"]                           = 623,
   ["Monastery Of Serene Harmony"]         = 624,
   ["Shimmerene Waterworks"]               = 625,
   ["Archon's Grove"]                      = 626,
   ["Artaeum"]                             = 627,
   ["Ceporah Tower"]                       = 628,
   ["Red Temple Catacombs"]                = 629,
   ["Rellenthil Sinkhole"]                 = 630,
   ["Cey-Tarn Keep"]                       = 631,
   ["The Gorge - Cey-Tarn Keep"]           = 632,
   ["The Vaults of Heinarwe"]              = 633,
   ["Altar Room"]                          = 634,
   ["Alinor"]                              = 635,
   ["Tor-Hame-Khard"]                      = 636,
   ["Alinor Royal Palace"]                 = 637,
   ["College of Psijics Ruins"]            = 638,
   ["Psijic Relic Vaults"]                 = 639,
   ["K'Tora's Mindscape"]                  = 640,
   ["Wasten Coraldale"]                    = 641,
   ["Eldbur Ruins"]                        = 642,
   ["Cainar's Mind Trap"]                  = 643,
   ["Miriya's Mind Trap"]                  = 644,
   ["Oriandra's Mind Trap"]                = 645,
   ["Direnni Acropolis"]                   = 646,
   ["Illumination Academy Stacks"]         = 647,
   ["Sea Keep"]                            = 648,
   ["Lillandril"]                          = 649,
   ["College of Sapiarchs Labyrinth"]      = 650,
   ["Saltbreeze Cave"]                     = 651,
   ["Alinor Outlaws Refuge"]               = 652,
   ["King's Haven Pass"]                   = 653,
   ["Coral-Splitter Caves"]                = 654,
   ["The Dreaming Cave"]                   = 655,
   ["Eton Nir Grotto"]                     = 656,
   ["The Spiral Skein"]                    = 657,
   ["Ebon Sanctum"]                        = 658,
   ["Traitor's Vault"]                     = 659,
   ["Evergloam"]                           = 660,
   ["Corgrad Wastes"]                      = 661,
   ["Cathedral of Webs"]                   = 662,
   ["Crystal Tower"]                       = 663,
	
   -- MURKMIRE
   ["The Sunless Hollow"]                  = 664,
   ["Norg-Tzel"]                           = 665,
   ["Norg-Tzel Xanmeer"]                   = 666,
   ["Lilmoth"]                             = 667,
   ["Murkmire"]                            = 668,
   ["Ixtaxh Xanmeer"]                      = 669,
   ["Bright-Throat Village"]               = 670,
   ["Blight Bog Sump"]                     = 671,
   ["Wither-Vault"]                        = 672,
   ["Dead-Water Village"]                  = 673,
   ["Tsofeer Cavern"]                      = 674,
   ["Tomb of Many Spears"]                 = 675,
   ["Swallowed Grove"]                     = 676,
   ["Teeth of Sithis"]                     = 677,
   ["Singing Grotto"]                      = 678,
   ["The Dreaming Nest"]                   = 679,
   ["The Mists"]                           = 680,
   ["Xul-Thuxis"]                          = 681,
   ["Root-Whisper Village"]                = 682,
   ["Vakka-Bok Xanmeer"]                   = 683,
   ["Deep-Root"]                           = 684,
   ["Remnant of Argon"]                    = 685,

   -- NORTHERN ELSWEYR
   ["New-Moons Chamber"]                   = 686,
   ["Dark-Moons Chamber"]                  = 687,
   ["Full-Moons Chamber"]                  = 688,
   ["Halls of Colossus"]                   = 689,
   ["Rimmen"]                              = 690,
   ["Northern Elsweyr"]                    = 691,
   ["Riverhold"]                           = 692,
   ["Abode of Ignominy"]                   = 693,
   ["Tomb of the Serpents"]                = 694,
   ["Smuggler's Hideout"]                  = 695,
   ["Predator Mesa"]                       = 696,
   ["Stitches"]                            = 697,
   ["Meirvale Keep Dungeons"]              = 698,
   ["Meirvale Keep Courtyard"]             = 699,
   ["Meirvale Keep Palace"]                = 700,
   ["Meirvale Keep Dugout"]                = 701,
   ["Sleepy Senche Mine"]                  = 702,
   ["Cicatrice Caverns"]                   = 703,
   ["Darkpool Mine"]                       = 704,
   ["Merryvale Sugar Farm Caves"]          = 705,
   ["Rimmen Palace Recesses"]              = 706,
   ["Desert Wind Caverns"]                 = 707,
   ["Hidden Moon Crypts"]                  = 708,
   ["Arum-Khal's Realm"]                   = 709,
   ["Hakoshae Tombs"]                      = 710,
   ["Tenarr Zelviit Ossuary"]              = 711,
   ["The Tangle"]                          = 712,
   ["Skooma Cat's Cloister"]               = 713,
   ["Rimmen Palace Crypts"]                = 714,
   ["Rimmen Palace"]                       = 715,
   ["Rimmen Palace Courtyard"]             = 716,
   ["Dov-Vahl Shrine"]                     = 717,
   ["Sepulcher of Mischance"]              = 718,
   ["Shadow Dance Temple"]                 = 719,
   ["Vault of Heavenly Scourge"]           = 720,
   ["Moon Gate of Anequina"]               = 721,
   ["Jode's Core"]                         = 722,
                    
   -- SOUTHERN ELSWEYR
   ["Wind Scour Temple"]                   = 723,
   ["Storm Talon Temple"]                  = 724,
   ["Dark Water Temple"]                   = 725,
   ["Vahlokzin's Domain"]                  = 726,
   ["Vahlokzin's Lair"]                    = 727,
   ["Senchal"]                             = 728,
   ["Senchal Palace"]                      = 729,
   ["Southern Elsweyr"]                    = 730,
   ["Tideholm"]                            = 731,
   ["Dragonguard Sanctum"]                 = 732,
   ["Moonlit Cove"]                        = 733,
   ["Passage of Dad'na Ghaten"]            = 734,
   ["Zazaradi's Quarry and Mine"]          = 735,
   ["Senchal Outlaws Refuge"]              = 736,
   ["Black Kiergo Arena"]                  = 737,
   ["Forsaken Citadel"]                    = 738,
   ["New Moon Fortress"]                   = 739,
   ["Halls of the Highmane"]               = 740,
   ["Path of Pride"]                       = 741,
   ["Doomstone Keep"]                      = 742,
   ["The Spilled Sand"]                    = 743,
   ["Dragonhold"]                          = 744,
   ["Jonelight Path"]                      = 745,
    
   -- Western Skyrim
   ["Riften Ratway"]                       = 746,
   ["Blackreach: Mzark Cavern"]            = 747,
   ["Palace Of Kings"]                     = 748,
   ["Western Skyrim"]                      = 749,
   ["Solitude"]                            = 750,
   ["Kilkreath Temple"]                    = 751,
   ["Shadowgreen"]                         = 752,
   ["Dragon Bridge Smuggler Caves"]        = 753,
   ["Dragonhome"]                          = 754,
   ["Mor Khazgur Mine"]                    = 755,
   ["Chillwind Depths"]                    = 756,
   ["Bleakridge Barrow"]                   = 757,
   ["Red Eagle Ridge"]                     = 758,
   ["Blackreach: Greymoor Caverns"]        = 759,
   ["Kagnthamz"]                           = 760,
   ["Verglas Hollow"]                      = 761,
   ["Frozen Coast"]                        = 762,
   ["Morthal Barrow"]                      = 763,
   ["Tzinghalis's Tower"]                  = 764,
   ["Lightless Hollow Mine"]               = 765,
   ["Blackreach: Dark Moon Grotto"]        = 766,
   ["The Scraps"]                          = 767,
   ["Midnight Barrow"]                     = 768,
   ["The Undergrove"]                      = 769,
   ["Greymoor Keep: West Wing"]            = 770,
   ["Greymoor Keep"]                       = 771,
   ["Gray Host Tunnels"]                   = 772,
    
   -- THE REACH
   ["Gray Host Sanctuary"]                 = 773,
   ["Grayhome"]                            = 774,
   ["Castle Grayhome"]                     = 775,
   ["Grayhome Ritual Chamber"]             = 776,
   ["The Reach"]                           = 777,
   ["Markarth"]                            = 778,
   ["Understone Keep"]                     = 779,
   ["Valthume"]                            = 780,
   ["Reachwind Depths"]                    = 781,
   ["Briar Rock Ruins"]                    = 782,
   ["Briar Rock Crypts"]                   = 783,
   ["Dead Crone Tower"]                    = 784,
   ["Sanuarach Mine"]                      = 785,
   ["Bthar-Zel"]                           = 786,
   ["Bthar-zel Vaults"]                    = 787,
   ["Blackreach: Arkthzand Cavern"]        = 788,
   ["Halls of Arkthzand"]                  = 789,
   ["Arkthzand Orrery"]                    = 790,
   ["Lost Valley Redoubt"]                 = 791,
   ["The Dark Descent"]                    = 792,
   ["Gloomreach"]                          = 793,
   ["Nighthollow Keep"]                    = 794,
   ["Chamber of the Dark Heart"]           = 795,
   ["Nchuand-Zel"]                         = 796,
   ["Nchuand-Zel Map"]                     = 797,
   ["Grayhaven"]                           = 798,
            
   -- Blackwood
   ["Imperial Cache Annex"]                = 799,
   ["Ne Salas Cache Annex"]                = 800,
   ["Imperial Sewers"]                     = 801,
   ["Deadlands"]                           = 802,
   ["Leyawiin"]                            = 803,
   ["Blackwood"]                           = 804,
   ["Undertow Cavern"]                     = 805,
   ["Borderwatch Sewers"]                  = 806,
   ["Borderwatch Courtyard"]               = 807,
   ["Borderwatch Keep"]                    = 808,
   ["Borderwatch Crypt"]                   = 809,
   ["Ayleid Ruins"]                        = 810,
   ["Veyond"]                              = 811,
   ["Arpenia"]                             = 812,
   ["Tidewater Cave"]                      = 813,
   ["Gideon"]                              = 814,
   ["Twyllbek Ruins"]                      = 815,
   ["Glenbridge Xanmeer"]                  = 816,
   ["Doomvault Porcixid"]                  = 817,
   ["Xal Irasotl"]                         = 818,
   ["Bloodrun Cave"]                       = 819,
   ["Welke"]                               = 820,
   ["Leyawiin Castle"]                     = 821,
   ["Xi-Tsei"]                             = 822,
   ["Stonewastes Keep"]                    = 823,
   ["Doomvault Capraxus"]                  = 824,
   ["Vandacia's Deadlands Keep"]           = 825,
   ["Vunalk"]                              = 826,
   ["Deadlands: The Ashen Forest"]         = 827,
   ["White Gold Tower Throne Room"]        = 828,
   ["Xynaa's Sanctuary"]                   = 829,
   ["Fort Redmane"]                        = 830,
   ["Ruction Ring"]                        = 831,
   ["Doomvault Vulpinaz Upper Level"]      = 832,
   ["Doomvault Vulpinaz Mid Level"]        = 833,
   ["Doomvault Vulpinaz Lower Level"]      = 834,
   ["Anchor Chamber"]                      = 835,
   ["Deepscorn Hollow"]                    = 836,

   -- Deadlands
   ["Lyranth's Hidden Lair"]               = 837,
   ["Waking Flame Camp"]                   = 838,
   ["Waking Flame Fargrave Conclave"]      = 839,
   ["Fargrave City District"]              = 840,
   ["The Deadlands"]                       = 841,
   ["The Bazaar"]                          = 842,
   ["The Shambles"]                        = 843,
   ["The Bathhouse"]                       = 844,
   ["The Collector's Villa"]               = 845,
   ["Burning Gyre Keep"]                   = 846,
   ["False Martyrs' Folly"]                = 847,
   ["Fleapits District"]                   = 848,
   ["Fort Grief"]                          = 849,
   ["Ardent Hope Outer Ward"]              = 850,
   ["Tower of Conviction"]                 = 851,
   ["Deadlight"]                           = 852,
   ["Deadlight Citadel"]                   = 853,
   ["Deadlight Summit"]                    = 854,
   ["Ardent Hope"]                         = 855,
   ["Ardent Hope Citadel"]                 = 856,
   ["The Path of Cinders"]                 = 857,
   ["Xarxes Crucible"]                     = 858,
   ["Brandfire Reformatory"]               = 859,
   ["Reformatory Forge"]                   = 860,
   ["Isle of Joys"]                        = 861,
   ["Hidden Chamber"]                      = 862,
   ["Destruction's Solace"]                = 863,
   ["Fort Sundercliff"]                    = 864,
    
   -- High Isle and Amenos
   ["Ascendant Order Hideout"]             = 865,
   ["Sareloth Grotto"]                     = 866,
   ["Sword's Rest Isle"]                   = 867,
   ["Sword's Rest Keep"]                   = 868,
   ["Sword's Rest Keep Basement"]          = 869,
   ["Gonfalon Bay"]                        = 870,
   ["Gonfalon Bay Outlaws Refuge"]         = 871,
   ["High Isle and Amenos"]                = 872,
   ["Abhain Chapel Crypts"]                = 873,
   ["Mysterious Cave"]                     = 874,
   ["Breakwater Cave"]                     = 875,
   ["Castle Navire"]                       = 876,
   ["Castle Navire Knight's Wing"]         = 877,
   ["Castle Navire Chapel"]                = 878,
   ["The Firepot"]                         = 879,
   ["Stonelore Grove"]                     = 880,
   ["The Undergrove"]                      = 881,
   ["Tarnished Grotto"]                    = 882,
   ["Garick's Rest"]                       = 883,
   ["Shipwreck Shoals"]                    = 884,
   ["Amenos Station"]                      = 885,
   ["Whalefall"]                           = 886,
   ["Systres Sisters Vault"]               = 887,
   ["Brokerock Mine"]                      = 888,
   ["Coral Cliffs"]                        = 889,
   ["Old Coin Fort"]                       = 890,
   ["Death's Valor Keep"]                  = 891,
   ["Mistmouth Cave"]                      = 892,
   ["Navire Dungeons"]                     = 893,
   ["All Flags Islet"]                     = 894,

   -- Firesong
   ["Eimhir's Cavern"]                     = 895,
   ["Glenmoril Ritual Site"]               = 896,
   ["Galen and Y'ffelon"]                  = 897,
   ["Suncleft Grotto"]                     = 898,
   ["Vastyr"]                              = 899,
   ["Vastyr Outlaws Refuge"]               = 900,
   ["Castle Mornard"]                      = 901,
   ["Draoife Dell"]                        = 902,
   ["Castle Tonnere Dungeons"]             = 903,
   ["Castle Tonnere Courtyard"]            = 904,
   ["Eldertide Hollow"]                    = 905,
   ["Embervine"]                           = 906,
   ["Sea Witch Sanctum"]                   = 907,
   ["Yfrees Path"]                         = 908,
   ["Clohaigh"]                            = 909,
   ["Fauns' Thicket"]                      = 910,
   ["Vastyr Cathedral District"]           = 911,
   ["Vastyr Old Druid Tunnels"]            = 912,
   ["Ivyhame"]                             = 913,
   ["Temple of Y'ffelon"]                  = 914,
   ["The Mad Maiden"]                      = 915,
   ["Y'ffelon"]                            = 916,
   ["Garrick's Rest Dungeons"]             = 917,
   ["Steadfast Manor Cellars"]             = 918,
   ["Ancient Druid Circle"]                = 919,
   ["Mount Firesong"]                      = 920,

   -- Telvanni Peninsula
   ["Emerald Glypic Vault"]                = 921,
   ["Shrine of the Golden Eye"]            = 922,
   ["Telvanni Peninsula"]                  = 923,
   ["Anchre Egg Mine"]                     = 924,
   ["Necrom"]                              = 925,
   ["Necrom Underways"]                    = 926,
   ["Necrom Necropolis"]                   = 927,
   ["Necropolis Catacombs"]                = 928,
   ["Necrom Outlaws Refuge"]               = 929,
   ["Tel Rendys"]                          = 930,
   ["Camonnaruhn"]                         = 931,
   ["Ald Isra"]                            = 932,
   ["Tel Dreloth"]                         = 933,
   ["Sailenmora Crypts"]                   = 934,
   ["Old Sailenmora Outpost"]              = 935,
   ["Tel Baro Cavern"]                     = 936,
   ["Kemel-Ze"]                            = 937,
   ["Alavelis Glass Mine"]                 = 938,
   ["Apocrypha"]                           = 939,
   ["Obscured Forum"]                      = 940,
   ["The Tranquil Catalog"]                = 941,
   ["Shrine of Hyrma Mora"]                = 942,
   ["Shrine of Herma-Mora"]                = 943,
   ["Shrine of Hermorah"]                  = 944,
   ["Catalog Boss Location"]               = 945,
   ["Pool of Inquiry"]                     = 946,
   ["The Disquiet Study"]                  = 947,
   ["Cipher's Midden"]                     = 948,
   ["Central Orphic Tunnels"]              = 949,
   ["Northern Orphic Tunnels"]             = 950,
   ["Cenotaph Fundament"]                  = 951,
   ["Courtyard of Communion"]              = 952,
   ["Cenotaph Rise"]                       = 953,
   ["Cathedral of Hermaeus Mora"]          = 954,
   ["The Crux"]                            = 955,
   ["Rectory Network"]                     = 956,
   ["Fathoms Drift"]                       = 957,
   ["The Forbidden Exhibit"]               = 958,
   ["The Infinite Panopticon"]             = 959,
   ["Tel Huulen Assembly Halls"]           = 960,
   ["The Mythos Vaults"]                   = 961,
   ["Quires Wind"]                         = 962,
   ["Apogee of the Tormenting Eye"]        = 963,
   ["The Sidereal Cloisters"]              = 964,
   ["The Mythos"]                          = 965,
   ["Gorne"]                               = 966,
   ["Underweave Courtyard"]                = 967,
   ["Underweave Nullifactory"]             = 968,
   ["Underweave Heart"]                    = 969,
   ["Martina's Sanctum"]                   = 970,
	
   -- Tutorial
   ["Balfiera Ruins"]                      = 971,
   ["Isle of Balfiera"]                    = 972,
   ["Keywright's Gallery"]                 = 973,
}

   -----------------------------------------
   -- HELPER FUNCTIONS
   -----------------------------------------

function Data:CollectMapIds()
	local sv = CGV.sv.profile
	sv.mapids = {}

	for i = 0,1000 do
		local loczone, _ = _G.GetZoneInfo(i)
		sv.mapids[loczone] = i
	end
end
